[package]
name = "idmrs"
version = "0.1.10"
edition = "2021"
authors = ["Hadi Cahyadi <cumulus13@gmail.com>"]
description = "Command line downloader via Internet Download Manager (IDM) on Windows"
license = "MIT"
repository = "https://github.com/cumulus13/idmrs"
readme = "README.md"
keywords = ["idm", "download", "windows", "cli"]
categories = ["command-line-utilities"]

[dependencies]
clap = { version = "4", features = ["derive"] }
anyhow = "1"
thiserror = "1"
colored = "2"
arboard = { version = "3", default-features = false }
ini = { version = "0.21", package = "rust-ini" }
dirs = "5"

[target.'cfg(windows)'.dependencies]
windows = { version = "0.58", features = [
    "Win32_Foundation",
    "Win32_System_Com",
    "Win32_System_Com_StructuredStorage", # <-- ADD THIS LINE
    "Win32_System_Variant",
    "Win32_System_Ole",
    "Win32_UI_WindowsAndMessaging",
    "Win32_Globalization",
    "Win32_System_LibraryLoader",
] }